### ISSUE TITLE
playcanvas-effekseer doesnt play on a Playcanvas Build

### ISSUE THREAD

**Issue by saadhaider78** [effekseer/playcanvas-effekseer#3]
When I make a build for the playcanvas-effekseer project, the effect doesn't run due to some issues of textures not loading:
![Capture](https://user-images.githubusercontent.com/21615560/116283480-5c9a7180-a7a5-11eb-8443-436b51f33af9.PNG)
So it wont work on a build: https://playcanv.as/b/n8OqHI1t/
but on launch it works perfectly:
https://launch.playcanvas.com/1139578?debug=true

I don't know what the issue happens when making a Playcanvas build.

**Comment by durswd** [comment]
It seems that ``` image.crossOrigin = "use-credentials"; ``` causes this error.
I will check it.

https://github.com/effekseer/EffekseerForWebGL/blob/master/src/js/effekseer.src.js#L402

**Comment by durswd** [comment]
I fixed the bug with this commit

https://github.com/effekseer/playcanvas-effekseer/commit/f053942c34bcdbd86de8a6a183856733aed8bf46
