### ISSUE TITLE
pc.Application.getApplication() return undefined effekseer-system can't parse!

### ISSUE THREAD

**Issue by yaoyutian** [effekseer/playcanvas-effekseer#4]
effekseer-system can't parse; won't load!
i tried to fork https://playcanvas.com/project/649529/overview/effekseersimplesample;
effekseer-system seems parsed default ,but when i press parse ,it failed.
<img width="1516" alt="2022-03-14" src="https://user-images.githubusercontent.com/10574966/158144073-4ce22796-2841-4403-93dc-c27e7f909365.png">

**Comment by durswd** [comment]
I fixed it

**Comment by yaoyutian** [comment]
thx , it works!
