### ISSUE TITLE
Effekseer integration no longer works since the Editor release 1.24.9

### ISSUE THREAD

**Issue by yaustar** [effekseer/playcanvas-effekseer#8]
See forum thread: https://forum.playcanvas.com/t/effekseer-integration-broken-since-editor-1-24-9-release/29790

When debugging the issue, I didn't understand why it was necessary to initialise the WASM manually with:

```
effekseer_nativeLib(params).then(function (module) {
```

As the WASM would be already initialised when loaded via the PlayCanvas WASM module loaders.

If you need support from the PlayCanvas team, please let us know and we can help with any questions or feature requests that you may have.

**Comment by durswd** [comment]
I will check it

**Comment by durswd** [comment]
I fixed it. Thank you.
